### ISSUE TITLE
ImportError: No module named django_google_storage.storage

### ISSUE THREAD

**Issue by vl4dt** [budurli/django-google-storage#13]
Got the following:

```bash
Internal Server Error: /admin/images/multiple/add/
Traceback (most recent call last):
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/wagtail/wagtailadmin/utils.py", line 93, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/views/decorators/vary.py", line 21, in inner_func
    response = func(*args, **kwargs)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/wagtail/wagtailimages/views/multiple.py", line 61, in add
    image.save()
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 973, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 931, in as_sql
    for obj in self.query.objs
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 315, in pre_save
    file.save(file.name, file, save=False)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 90, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/wagtail/wagtailimages/models.py", line 46, in get_upload_to
    filename = instance.file.field.storage.get_valid_name(filename)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/utils/functional.py", line 226, in inner
    self._setup()
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/core/files/storage.py", line 334, in _setup
    self._wrapped = get_storage_class()()
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/core/files/storage.py", line 329, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/home/ricardo/.virtualenvs/wagtail/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_google_storage.storage
```

And:
```bash
~/projects/wagtail/oc master*
(wagtail)❯ pip freeze | grep google
django-google-storage==0.3
                                
~/projects/wagtail/oc master*
(wagtail)❯ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django-google-storage
  File "<stdin>", line 1
    import django-google-storage
                 ^
SyntaxError: invalid syntax
>>> import django_google_storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named django_google_storage
>>> 
```

**Comment by vl4dt** [comment]
The directory name is installed with name 'django-google-storage', should be 'django_google_storage',

**Comment by sandino** [comment]
Why closed? The issue is still there.

**Comment by vl4dt** [comment]
About this issue, I fixed the thing, there was a problem with the installation, in the file it is stored under:

***django-google-storage***

However you can't import a module named like that, so you have to change the directory name to:

***django_google_storage***

Of course the problem must lie within the installer
